name: fashion_hub
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  hive_flutter: ^1.1.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.4
  multi_select_flutter: ^4.1.3
  uuid: ^4.5.1
  dartz: ^0.10.1
  path_provider: ^2.1.5
  equatable: ^2.0.7
  image_picker: ^1.1.2
  awesome_dio_interceptor: ^1.3.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.1
  permission_handler: ^11.3.1
  json_serializable: ^6.9.0
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  carousel_slider: ^5.0.0
  sensors_plus: ^6.1.1
  proximity_sensor: ^1.3.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  test_cov_console: ^0.2.2

  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/fashion_hub_logo.png 
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/carousel_img/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 300
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
          weight: 300
